/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../../pages/__root"
import { Route as protectedRouteRouteImport } from "./../../pages/(protected)/route"
import { Route as protectedIndexRouteImport } from "./../../pages/(protected)/index"
import { Route as AuthSignUpRouteImport } from "./../../pages/auth/sign-up"
import { Route as AuthSignInRouteImport } from "./../../pages/auth/sign-in"
import { Route as protectedSubscriptionsIndexRouteImport } from "./../../pages/(protected)/subscriptions/index"
import { Route as protectedSettingsIndexRouteImport } from "./../../pages/(protected)/settings/index"
import { Route as protectedSubscriptionsAddRouteImport } from "./../../pages/(protected)/subscriptions/add"
import { Route as protectedSettingsNotificationsRouteImport } from "./../../pages/(protected)/settings/notifications"
import { Route as protectedSettingsGeneralRouteImport } from "./../../pages/(protected)/settings/general"
import { Route as protectedSettingsAccountRouteImport } from "./../../pages/(protected)/settings/account"
import { Route as protectedSubscriptionsIdIndexRouteImport } from "./../../pages/(protected)/subscriptions/$id/index"
import { Route as protectedSubscriptionsIdEditRouteImport } from "./../../pages/(protected)/subscriptions/$id/edit"

const protectedRouteRoute = protectedRouteRouteImport.update({
  id: "/(protected)",
  getParentRoute: () => rootRouteImport,
} as any)
const protectedIndexRoute = protectedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => protectedRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: "/auth/sign-up",
  path: "/auth/sign-up",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: "/auth/sign-in",
  path: "/auth/sign-in",
  getParentRoute: () => rootRouteImport,
} as any)
const protectedSubscriptionsIndexRoute =
  protectedSubscriptionsIndexRouteImport.update({
    id: "/subscriptions/",
    path: "/subscriptions/",
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedSettingsIndexRoute = protectedSettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSubscriptionsAddRoute =
  protectedSubscriptionsAddRouteImport.update({
    id: "/subscriptions/add",
    path: "/subscriptions/add",
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedSettingsNotificationsRoute =
  protectedSettingsNotificationsRouteImport.update({
    id: "/settings/notifications",
    path: "/settings/notifications",
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedSettingsGeneralRoute =
  protectedSettingsGeneralRouteImport.update({
    id: "/settings/general",
    path: "/settings/general",
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedSettingsAccountRoute =
  protectedSettingsAccountRouteImport.update({
    id: "/settings/account",
    path: "/settings/account",
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedSubscriptionsIdIndexRoute =
  protectedSubscriptionsIdIndexRouteImport.update({
    id: "/subscriptions/$id/",
    path: "/subscriptions/$id/",
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedSubscriptionsIdEditRoute =
  protectedSubscriptionsIdEditRouteImport.update({
    id: "/subscriptions/$id/edit",
    path: "/subscriptions/$id/edit",
    getParentRoute: () => protectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/auth/sign-in": typeof AuthSignInRoute
  "/auth/sign-up": typeof AuthSignUpRoute
  "/": typeof protectedIndexRoute
  "/settings/account": typeof protectedSettingsAccountRoute
  "/settings/general": typeof protectedSettingsGeneralRoute
  "/settings/notifications": typeof protectedSettingsNotificationsRoute
  "/subscriptions/add": typeof protectedSubscriptionsAddRoute
  "/settings/": typeof protectedSettingsIndexRoute
  "/subscriptions/": typeof protectedSubscriptionsIndexRoute
  "/subscriptions/$id/edit": typeof protectedSubscriptionsIdEditRoute
  "/subscriptions/$id/": typeof protectedSubscriptionsIdIndexRoute
}
export interface FileRoutesByTo {
  "/auth/sign-in": typeof AuthSignInRoute
  "/auth/sign-up": typeof AuthSignUpRoute
  "/": typeof protectedIndexRoute
  "/settings/account": typeof protectedSettingsAccountRoute
  "/settings/general": typeof protectedSettingsGeneralRoute
  "/settings/notifications": typeof protectedSettingsNotificationsRoute
  "/subscriptions/add": typeof protectedSubscriptionsAddRoute
  "/settings": typeof protectedSettingsIndexRoute
  "/subscriptions": typeof protectedSubscriptionsIndexRoute
  "/subscriptions/$id/edit": typeof protectedSubscriptionsIdEditRoute
  "/subscriptions/$id": typeof protectedSubscriptionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/(protected)": typeof protectedRouteRouteWithChildren
  "/auth/sign-in": typeof AuthSignInRoute
  "/auth/sign-up": typeof AuthSignUpRoute
  "/(protected)/": typeof protectedIndexRoute
  "/(protected)/settings/account": typeof protectedSettingsAccountRoute
  "/(protected)/settings/general": typeof protectedSettingsGeneralRoute
  "/(protected)/settings/notifications": typeof protectedSettingsNotificationsRoute
  "/(protected)/subscriptions/add": typeof protectedSubscriptionsAddRoute
  "/(protected)/settings/": typeof protectedSettingsIndexRoute
  "/(protected)/subscriptions/": typeof protectedSubscriptionsIndexRoute
  "/(protected)/subscriptions/$id/edit": typeof protectedSubscriptionsIdEditRoute
  "/(protected)/subscriptions/$id/": typeof protectedSubscriptionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/"
    | "/settings/account"
    | "/settings/general"
    | "/settings/notifications"
    | "/subscriptions/add"
    | "/settings/"
    | "/subscriptions/"
    | "/subscriptions/$id/edit"
    | "/subscriptions/$id/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/"
    | "/settings/account"
    | "/settings/general"
    | "/settings/notifications"
    | "/subscriptions/add"
    | "/settings"
    | "/subscriptions"
    | "/subscriptions/$id/edit"
    | "/subscriptions/$id"
  id:
    | "__root__"
    | "/(protected)"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/(protected)/"
    | "/(protected)/settings/account"
    | "/(protected)/settings/general"
    | "/(protected)/settings/notifications"
    | "/(protected)/subscriptions/add"
    | "/(protected)/settings/"
    | "/(protected)/subscriptions/"
    | "/(protected)/subscriptions/$id/edit"
    | "/(protected)/subscriptions/$id/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(protected)": {
      id: "/(protected)"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(protected)/": {
      id: "/(protected)/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof protectedIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/auth/sign-up": {
      id: "/auth/sign-up"
      path: "/auth/sign-up"
      fullPath: "/auth/sign-up"
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/sign-in": {
      id: "/auth/sign-in"
      path: "/auth/sign-in"
      fullPath: "/auth/sign-in"
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(protected)/subscriptions/": {
      id: "/(protected)/subscriptions/"
      path: "/subscriptions"
      fullPath: "/subscriptions/"
      preLoaderRoute: typeof protectedSubscriptionsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/settings/": {
      id: "/(protected)/settings/"
      path: "/settings"
      fullPath: "/settings/"
      preLoaderRoute: typeof protectedSettingsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/subscriptions/add": {
      id: "/(protected)/subscriptions/add"
      path: "/subscriptions/add"
      fullPath: "/subscriptions/add"
      preLoaderRoute: typeof protectedSubscriptionsAddRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/settings/notifications": {
      id: "/(protected)/settings/notifications"
      path: "/settings/notifications"
      fullPath: "/settings/notifications"
      preLoaderRoute: typeof protectedSettingsNotificationsRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/settings/general": {
      id: "/(protected)/settings/general"
      path: "/settings/general"
      fullPath: "/settings/general"
      preLoaderRoute: typeof protectedSettingsGeneralRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/settings/account": {
      id: "/(protected)/settings/account"
      path: "/settings/account"
      fullPath: "/settings/account"
      preLoaderRoute: typeof protectedSettingsAccountRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/subscriptions/$id/": {
      id: "/(protected)/subscriptions/$id/"
      path: "/subscriptions/$id"
      fullPath: "/subscriptions/$id/"
      preLoaderRoute: typeof protectedSubscriptionsIdIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/subscriptions/$id/edit": {
      id: "/(protected)/subscriptions/$id/edit"
      path: "/subscriptions/$id/edit"
      fullPath: "/subscriptions/$id/edit"
      preLoaderRoute: typeof protectedSubscriptionsIdEditRouteImport
      parentRoute: typeof protectedRouteRoute
    }
  }
}

interface protectedRouteRouteChildren {
  protectedIndexRoute: typeof protectedIndexRoute
  protectedSettingsAccountRoute: typeof protectedSettingsAccountRoute
  protectedSettingsGeneralRoute: typeof protectedSettingsGeneralRoute
  protectedSettingsNotificationsRoute: typeof protectedSettingsNotificationsRoute
  protectedSubscriptionsAddRoute: typeof protectedSubscriptionsAddRoute
  protectedSettingsIndexRoute: typeof protectedSettingsIndexRoute
  protectedSubscriptionsIndexRoute: typeof protectedSubscriptionsIndexRoute
  protectedSubscriptionsIdEditRoute: typeof protectedSubscriptionsIdEditRoute
  protectedSubscriptionsIdIndexRoute: typeof protectedSubscriptionsIdIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedIndexRoute: protectedIndexRoute,
  protectedSettingsAccountRoute: protectedSettingsAccountRoute,
  protectedSettingsGeneralRoute: protectedSettingsGeneralRoute,
  protectedSettingsNotificationsRoute: protectedSettingsNotificationsRoute,
  protectedSubscriptionsAddRoute: protectedSubscriptionsAddRoute,
  protectedSettingsIndexRoute: protectedSettingsIndexRoute,
  protectedSubscriptionsIndexRoute: protectedSubscriptionsIndexRoute,
  protectedSubscriptionsIdEditRoute: protectedSubscriptionsIdEditRoute,
  protectedSubscriptionsIdIndexRoute: protectedSubscriptionsIdIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedRouteRoute: protectedRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
