/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../../pages/__root"
import { Route as DemoRouteRouteImport } from "./../../pages/demo/route"
import { Route as protectedRouteRouteImport } from "./../../pages/(protected)/route"
import { Route as DemoIndexRouteImport } from "./../../pages/demo/index"
import { Route as protectedIndexRouteImport } from "./../../pages/(protected)/index"
import { Route as protectedDevRouteRouteImport } from "./../../pages/(protected)/dev/route"
import { Route as DemoSubscriptionsIndexRouteImport } from "./../../pages/demo/subscriptions/index"
import { Route as protectedSubscriptionsIndexRouteImport } from "./../../pages/(protected)/subscriptions/index"
import { Route as protectedSettingsIndexRouteImport } from "./../../pages/(protected)/settings/index"
import { Route as protectedDevIndexRouteImport } from "./../../pages/(protected)/dev/index"
import { Route as AuthSignUpSplatRouteImport } from "./../../pages/auth/sign-up/$"
import { Route as AuthSignInSplatRouteImport } from "./../../pages/auth/sign-in/$"
import { Route as protectedSubscriptionsCompareRouteImport } from "./../../pages/(protected)/subscriptions/compare"
import { Route as protectedSubscriptionsAddRouteImport } from "./../../pages/(protected)/subscriptions/add"
import { Route as protectedSettingsNotificationsRouteImport } from "./../../pages/(protected)/settings/notifications"
import { Route as protectedSettingsGeneralRouteImport } from "./../../pages/(protected)/settings/general"
import { Route as protectedSettingsCategoriesRouteImport } from "./../../pages/(protected)/settings/categories"
import { Route as protectedSettingsBillingRouteImport } from "./../../pages/(protected)/settings/billing"
import { Route as protectedSettingsAccountRouteImport } from "./../../pages/(protected)/settings/account"
import { Route as protectedDevNotificationsRouteImport } from "./../../pages/(protected)/dev/notifications"
import { Route as protectedSettingsGroupRouteRouteImport } from "./../../pages/(protected)/settings/group/route"
import { Route as protectedSubscriptionsIdIndexRouteImport } from "./../../pages/(protected)/subscriptions/$id/index"
import { Route as protectedSubscriptionsIdEditRouteImport } from "./../../pages/(protected)/subscriptions/$id/edit"
import { Route as protectedSettingsCategoriesGenerateRouteImport } from "./../../pages/(protected)/settings/categories/generate"

const DemoRouteRoute = DemoRouteRouteImport.update({
  id: "/demo",
  path: "/demo",
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: "/(protected)",
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DemoRouteRoute,
} as any)
const protectedIndexRoute = protectedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDevRouteRoute = protectedDevRouteRouteImport.update({
  id: "/dev",
  path: "/dev",
  getParentRoute: () => protectedRouteRoute,
} as any)
const DemoSubscriptionsIndexRoute = DemoSubscriptionsIndexRouteImport.update({
  id: "/subscriptions/",
  path: "/subscriptions/",
  getParentRoute: () => DemoRouteRoute,
} as any)
const protectedSubscriptionsIndexRoute =
  protectedSubscriptionsIndexRouteImport.update({
    id: "/subscriptions/",
    path: "/subscriptions/",
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedSettingsIndexRoute = protectedSettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDevIndexRoute = protectedDevIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => protectedDevRouteRoute,
} as any)
const AuthSignUpSplatRoute = AuthSignUpSplatRouteImport.update({
  id: "/auth/sign-up/$",
  path: "/auth/sign-up/$",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInSplatRoute = AuthSignInSplatRouteImport.update({
  id: "/auth/sign-in/$",
  path: "/auth/sign-in/$",
  getParentRoute: () => rootRouteImport,
} as any)
const protectedSubscriptionsCompareRoute =
  protectedSubscriptionsCompareRouteImport.update({
    id: "/subscriptions/compare",
    path: "/subscriptions/compare",
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedSubscriptionsAddRoute =
  protectedSubscriptionsAddRouteImport.update({
    id: "/subscriptions/add",
    path: "/subscriptions/add",
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedSettingsNotificationsRoute =
  protectedSettingsNotificationsRouteImport.update({
    id: "/settings/notifications",
    path: "/settings/notifications",
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedSettingsGeneralRoute =
  protectedSettingsGeneralRouteImport.update({
    id: "/settings/general",
    path: "/settings/general",
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedSettingsCategoriesRoute =
  protectedSettingsCategoriesRouteImport.update({
    id: "/settings/categories",
    path: "/settings/categories",
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedSettingsBillingRoute =
  protectedSettingsBillingRouteImport.update({
    id: "/settings/billing",
    path: "/settings/billing",
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedSettingsAccountRoute =
  protectedSettingsAccountRouteImport.update({
    id: "/settings/account",
    path: "/settings/account",
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedDevNotificationsRoute =
  protectedDevNotificationsRouteImport.update({
    id: "/notifications",
    path: "/notifications",
    getParentRoute: () => protectedDevRouteRoute,
  } as any)
const protectedSettingsGroupRouteRoute =
  protectedSettingsGroupRouteRouteImport.update({
    id: "/settings/group",
    path: "/settings/group",
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedSubscriptionsIdIndexRoute =
  protectedSubscriptionsIdIndexRouteImport.update({
    id: "/subscriptions/$id/",
    path: "/subscriptions/$id/",
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedSubscriptionsIdEditRoute =
  protectedSubscriptionsIdEditRouteImport.update({
    id: "/subscriptions/$id/edit",
    path: "/subscriptions/$id/edit",
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedSettingsCategoriesGenerateRoute =
  protectedSettingsCategoriesGenerateRouteImport.update({
    id: "/generate",
    path: "/generate",
    getParentRoute: () => protectedSettingsCategoriesRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/demo": typeof DemoRouteRouteWithChildren
  "/dev": typeof protectedDevRouteRouteWithChildren
  "/": typeof protectedIndexRoute
  "/demo/": typeof DemoIndexRoute
  "/settings/group": typeof protectedSettingsGroupRouteRoute
  "/dev/notifications": typeof protectedDevNotificationsRoute
  "/settings/account": typeof protectedSettingsAccountRoute
  "/settings/billing": typeof protectedSettingsBillingRoute
  "/settings/categories": typeof protectedSettingsCategoriesRouteWithChildren
  "/settings/general": typeof protectedSettingsGeneralRoute
  "/settings/notifications": typeof protectedSettingsNotificationsRoute
  "/subscriptions/add": typeof protectedSubscriptionsAddRoute
  "/subscriptions/compare": typeof protectedSubscriptionsCompareRoute
  "/auth/sign-in/$": typeof AuthSignInSplatRoute
  "/auth/sign-up/$": typeof AuthSignUpSplatRoute
  "/dev/": typeof protectedDevIndexRoute
  "/settings/": typeof protectedSettingsIndexRoute
  "/subscriptions/": typeof protectedSubscriptionsIndexRoute
  "/demo/subscriptions/": typeof DemoSubscriptionsIndexRoute
  "/settings/categories/generate": typeof protectedSettingsCategoriesGenerateRoute
  "/subscriptions/$id/edit": typeof protectedSubscriptionsIdEditRoute
  "/subscriptions/$id/": typeof protectedSubscriptionsIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof protectedIndexRoute
  "/demo": typeof DemoIndexRoute
  "/settings/group": typeof protectedSettingsGroupRouteRoute
  "/dev/notifications": typeof protectedDevNotificationsRoute
  "/settings/account": typeof protectedSettingsAccountRoute
  "/settings/billing": typeof protectedSettingsBillingRoute
  "/settings/categories": typeof protectedSettingsCategoriesRouteWithChildren
  "/settings/general": typeof protectedSettingsGeneralRoute
  "/settings/notifications": typeof protectedSettingsNotificationsRoute
  "/subscriptions/add": typeof protectedSubscriptionsAddRoute
  "/subscriptions/compare": typeof protectedSubscriptionsCompareRoute
  "/auth/sign-in/$": typeof AuthSignInSplatRoute
  "/auth/sign-up/$": typeof AuthSignUpSplatRoute
  "/dev": typeof protectedDevIndexRoute
  "/settings": typeof protectedSettingsIndexRoute
  "/subscriptions": typeof protectedSubscriptionsIndexRoute
  "/demo/subscriptions": typeof DemoSubscriptionsIndexRoute
  "/settings/categories/generate": typeof protectedSettingsCategoriesGenerateRoute
  "/subscriptions/$id/edit": typeof protectedSubscriptionsIdEditRoute
  "/subscriptions/$id": typeof protectedSubscriptionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/(protected)": typeof protectedRouteRouteWithChildren
  "/demo": typeof DemoRouteRouteWithChildren
  "/(protected)/dev": typeof protectedDevRouteRouteWithChildren
  "/(protected)/": typeof protectedIndexRoute
  "/demo/": typeof DemoIndexRoute
  "/(protected)/settings/group": typeof protectedSettingsGroupRouteRoute
  "/(protected)/dev/notifications": typeof protectedDevNotificationsRoute
  "/(protected)/settings/account": typeof protectedSettingsAccountRoute
  "/(protected)/settings/billing": typeof protectedSettingsBillingRoute
  "/(protected)/settings/categories": typeof protectedSettingsCategoriesRouteWithChildren
  "/(protected)/settings/general": typeof protectedSettingsGeneralRoute
  "/(protected)/settings/notifications": typeof protectedSettingsNotificationsRoute
  "/(protected)/subscriptions/add": typeof protectedSubscriptionsAddRoute
  "/(protected)/subscriptions/compare": typeof protectedSubscriptionsCompareRoute
  "/auth/sign-in/$": typeof AuthSignInSplatRoute
  "/auth/sign-up/$": typeof AuthSignUpSplatRoute
  "/(protected)/dev/": typeof protectedDevIndexRoute
  "/(protected)/settings/": typeof protectedSettingsIndexRoute
  "/(protected)/subscriptions/": typeof protectedSubscriptionsIndexRoute
  "/demo/subscriptions/": typeof DemoSubscriptionsIndexRoute
  "/(protected)/settings/categories/generate": typeof protectedSettingsCategoriesGenerateRoute
  "/(protected)/subscriptions/$id/edit": typeof protectedSubscriptionsIdEditRoute
  "/(protected)/subscriptions/$id/": typeof protectedSubscriptionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/demo"
    | "/dev"
    | "/"
    | "/demo/"
    | "/settings/group"
    | "/dev/notifications"
    | "/settings/account"
    | "/settings/billing"
    | "/settings/categories"
    | "/settings/general"
    | "/settings/notifications"
    | "/subscriptions/add"
    | "/subscriptions/compare"
    | "/auth/sign-in/$"
    | "/auth/sign-up/$"
    | "/dev/"
    | "/settings/"
    | "/subscriptions/"
    | "/demo/subscriptions/"
    | "/settings/categories/generate"
    | "/subscriptions/$id/edit"
    | "/subscriptions/$id/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/demo"
    | "/settings/group"
    | "/dev/notifications"
    | "/settings/account"
    | "/settings/billing"
    | "/settings/categories"
    | "/settings/general"
    | "/settings/notifications"
    | "/subscriptions/add"
    | "/subscriptions/compare"
    | "/auth/sign-in/$"
    | "/auth/sign-up/$"
    | "/dev"
    | "/settings"
    | "/subscriptions"
    | "/demo/subscriptions"
    | "/settings/categories/generate"
    | "/subscriptions/$id/edit"
    | "/subscriptions/$id"
  id:
    | "__root__"
    | "/(protected)"
    | "/demo"
    | "/(protected)/dev"
    | "/(protected)/"
    | "/demo/"
    | "/(protected)/settings/group"
    | "/(protected)/dev/notifications"
    | "/(protected)/settings/account"
    | "/(protected)/settings/billing"
    | "/(protected)/settings/categories"
    | "/(protected)/settings/general"
    | "/(protected)/settings/notifications"
    | "/(protected)/subscriptions/add"
    | "/(protected)/subscriptions/compare"
    | "/auth/sign-in/$"
    | "/auth/sign-up/$"
    | "/(protected)/dev/"
    | "/(protected)/settings/"
    | "/(protected)/subscriptions/"
    | "/demo/subscriptions/"
    | "/(protected)/settings/categories/generate"
    | "/(protected)/subscriptions/$id/edit"
    | "/(protected)/subscriptions/$id/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  DemoRouteRoute: typeof DemoRouteRouteWithChildren
  AuthSignInSplatRoute: typeof AuthSignInSplatRoute
  AuthSignUpSplatRoute: typeof AuthSignUpSplatRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/demo": {
      id: "/demo"
      path: "/demo"
      fullPath: "/demo"
      preLoaderRoute: typeof DemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(protected)": {
      id: "/(protected)"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/demo/": {
      id: "/demo/"
      path: "/"
      fullPath: "/demo/"
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    "/(protected)/": {
      id: "/(protected)/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof protectedIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/dev": {
      id: "/(protected)/dev"
      path: "/dev"
      fullPath: "/dev"
      preLoaderRoute: typeof protectedDevRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/demo/subscriptions/": {
      id: "/demo/subscriptions/"
      path: "/subscriptions"
      fullPath: "/demo/subscriptions/"
      preLoaderRoute: typeof DemoSubscriptionsIndexRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    "/(protected)/subscriptions/": {
      id: "/(protected)/subscriptions/"
      path: "/subscriptions"
      fullPath: "/subscriptions/"
      preLoaderRoute: typeof protectedSubscriptionsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/settings/": {
      id: "/(protected)/settings/"
      path: "/settings"
      fullPath: "/settings/"
      preLoaderRoute: typeof protectedSettingsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/dev/": {
      id: "/(protected)/dev/"
      path: "/"
      fullPath: "/dev/"
      preLoaderRoute: typeof protectedDevIndexRouteImport
      parentRoute: typeof protectedDevRouteRoute
    }
    "/auth/sign-up/$": {
      id: "/auth/sign-up/$"
      path: "/auth/sign-up/$"
      fullPath: "/auth/sign-up/$"
      preLoaderRoute: typeof AuthSignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/sign-in/$": {
      id: "/auth/sign-in/$"
      path: "/auth/sign-in/$"
      fullPath: "/auth/sign-in/$"
      preLoaderRoute: typeof AuthSignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(protected)/subscriptions/compare": {
      id: "/(protected)/subscriptions/compare"
      path: "/subscriptions/compare"
      fullPath: "/subscriptions/compare"
      preLoaderRoute: typeof protectedSubscriptionsCompareRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/subscriptions/add": {
      id: "/(protected)/subscriptions/add"
      path: "/subscriptions/add"
      fullPath: "/subscriptions/add"
      preLoaderRoute: typeof protectedSubscriptionsAddRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/settings/notifications": {
      id: "/(protected)/settings/notifications"
      path: "/settings/notifications"
      fullPath: "/settings/notifications"
      preLoaderRoute: typeof protectedSettingsNotificationsRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/settings/general": {
      id: "/(protected)/settings/general"
      path: "/settings/general"
      fullPath: "/settings/general"
      preLoaderRoute: typeof protectedSettingsGeneralRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/settings/categories": {
      id: "/(protected)/settings/categories"
      path: "/settings/categories"
      fullPath: "/settings/categories"
      preLoaderRoute: typeof protectedSettingsCategoriesRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/settings/billing": {
      id: "/(protected)/settings/billing"
      path: "/settings/billing"
      fullPath: "/settings/billing"
      preLoaderRoute: typeof protectedSettingsBillingRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/settings/account": {
      id: "/(protected)/settings/account"
      path: "/settings/account"
      fullPath: "/settings/account"
      preLoaderRoute: typeof protectedSettingsAccountRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/dev/notifications": {
      id: "/(protected)/dev/notifications"
      path: "/notifications"
      fullPath: "/dev/notifications"
      preLoaderRoute: typeof protectedDevNotificationsRouteImport
      parentRoute: typeof protectedDevRouteRoute
    }
    "/(protected)/settings/group": {
      id: "/(protected)/settings/group"
      path: "/settings/group"
      fullPath: "/settings/group"
      preLoaderRoute: typeof protectedSettingsGroupRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/subscriptions/$id/": {
      id: "/(protected)/subscriptions/$id/"
      path: "/subscriptions/$id"
      fullPath: "/subscriptions/$id/"
      preLoaderRoute: typeof protectedSubscriptionsIdIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/subscriptions/$id/edit": {
      id: "/(protected)/subscriptions/$id/edit"
      path: "/subscriptions/$id/edit"
      fullPath: "/subscriptions/$id/edit"
      preLoaderRoute: typeof protectedSubscriptionsIdEditRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    "/(protected)/settings/categories/generate": {
      id: "/(protected)/settings/categories/generate"
      path: "/generate"
      fullPath: "/settings/categories/generate"
      preLoaderRoute: typeof protectedSettingsCategoriesGenerateRouteImport
      parentRoute: typeof protectedSettingsCategoriesRoute
    }
  }
}

interface protectedDevRouteRouteChildren {
  protectedDevNotificationsRoute: typeof protectedDevNotificationsRoute
  protectedDevIndexRoute: typeof protectedDevIndexRoute
}

const protectedDevRouteRouteChildren: protectedDevRouteRouteChildren = {
  protectedDevNotificationsRoute: protectedDevNotificationsRoute,
  protectedDevIndexRoute: protectedDevIndexRoute,
}

const protectedDevRouteRouteWithChildren =
  protectedDevRouteRoute._addFileChildren(protectedDevRouteRouteChildren)

interface protectedSettingsCategoriesRouteChildren {
  protectedSettingsCategoriesGenerateRoute: typeof protectedSettingsCategoriesGenerateRoute
}

const protectedSettingsCategoriesRouteChildren: protectedSettingsCategoriesRouteChildren =
  {
    protectedSettingsCategoriesGenerateRoute:
      protectedSettingsCategoriesGenerateRoute,
  }

const protectedSettingsCategoriesRouteWithChildren =
  protectedSettingsCategoriesRoute._addFileChildren(
    protectedSettingsCategoriesRouteChildren,
  )

interface protectedRouteRouteChildren {
  protectedDevRouteRoute: typeof protectedDevRouteRouteWithChildren
  protectedIndexRoute: typeof protectedIndexRoute
  protectedSettingsGroupRouteRoute: typeof protectedSettingsGroupRouteRoute
  protectedSettingsAccountRoute: typeof protectedSettingsAccountRoute
  protectedSettingsBillingRoute: typeof protectedSettingsBillingRoute
  protectedSettingsCategoriesRoute: typeof protectedSettingsCategoriesRouteWithChildren
  protectedSettingsGeneralRoute: typeof protectedSettingsGeneralRoute
  protectedSettingsNotificationsRoute: typeof protectedSettingsNotificationsRoute
  protectedSubscriptionsAddRoute: typeof protectedSubscriptionsAddRoute
  protectedSubscriptionsCompareRoute: typeof protectedSubscriptionsCompareRoute
  protectedSettingsIndexRoute: typeof protectedSettingsIndexRoute
  protectedSubscriptionsIndexRoute: typeof protectedSubscriptionsIndexRoute
  protectedSubscriptionsIdEditRoute: typeof protectedSubscriptionsIdEditRoute
  protectedSubscriptionsIdIndexRoute: typeof protectedSubscriptionsIdIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedDevRouteRoute: protectedDevRouteRouteWithChildren,
  protectedIndexRoute: protectedIndexRoute,
  protectedSettingsGroupRouteRoute: protectedSettingsGroupRouteRoute,
  protectedSettingsAccountRoute: protectedSettingsAccountRoute,
  protectedSettingsBillingRoute: protectedSettingsBillingRoute,
  protectedSettingsCategoriesRoute:
    protectedSettingsCategoriesRouteWithChildren,
  protectedSettingsGeneralRoute: protectedSettingsGeneralRoute,
  protectedSettingsNotificationsRoute: protectedSettingsNotificationsRoute,
  protectedSubscriptionsAddRoute: protectedSubscriptionsAddRoute,
  protectedSubscriptionsCompareRoute: protectedSubscriptionsCompareRoute,
  protectedSettingsIndexRoute: protectedSettingsIndexRoute,
  protectedSubscriptionsIndexRoute: protectedSubscriptionsIndexRoute,
  protectedSubscriptionsIdEditRoute: protectedSubscriptionsIdEditRoute,
  protectedSubscriptionsIdIndexRoute: protectedSubscriptionsIdIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface DemoRouteRouteChildren {
  DemoIndexRoute: typeof DemoIndexRoute
  DemoSubscriptionsIndexRoute: typeof DemoSubscriptionsIndexRoute
}

const DemoRouteRouteChildren: DemoRouteRouteChildren = {
  DemoIndexRoute: DemoIndexRoute,
  DemoSubscriptionsIndexRoute: DemoSubscriptionsIndexRoute,
}

const DemoRouteRouteWithChildren = DemoRouteRoute._addFileChildren(
  DemoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedRouteRoute: protectedRouteRouteWithChildren,
  DemoRouteRoute: DemoRouteRouteWithChildren,
  AuthSignInSplatRoute: AuthSignInSplatRoute,
  AuthSignUpSplatRoute: AuthSignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
