// Every currency SubEye can hold, and the only place the set is defined.
//
// Generated from CLDR against the FX table's own key set (`store/fx-seed.json`):
// a code with no rate would convert 1:1 and silently under-report every total, so
// the catalogue can never be wider than what the rate document carries. Retired
// codes — the euro-zone legacy set, the 2000s redenominations — plus precious
// metals, fund codes and the crypto tickers the FX API also publishes are left
// out: they all carry a rate, but nobody is billed in them.
//
// `symbol` is the en-US narrow symbol, which for a third of these simply IS the
// code (AED, BGN, CHF…). The picker hides it there rather than printing the same
// three letters twice.
export const CURRENCIES: Record<string, { name: string; symbol: string }> = {
  aed: { name: "United Arab Emirates Dirham", symbol: "AED" },
  afn: { name: "Afghan Afghani", symbol: "؋" },
  all: { name: "Albanian Lek", symbol: "ALL" },
  amd: { name: "Armenian Dram", symbol: "֏" },
  aoa: { name: "Angolan Kwanza", symbol: "Kz" },
  ars: { name: "Argentine Peso", symbol: "$" },
  aud: { name: "Australian Dollar", symbol: "$" },
  awg: { name: "Aruban Florin", symbol: "AWG" },
  azn: { name: "Azerbaijani Manat", symbol: "₼" },
  bam: { name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
  bbd: { name: "Barbadian Dollar", symbol: "$" },
  bdt: { name: "Bangladeshi Taka", symbol: "৳" },
  bgn: { name: "Bulgarian Lev", symbol: "BGN" },
  bhd: { name: "Bahraini Dinar", symbol: "BHD" },
  bif: { name: "Burundian Franc", symbol: "BIF" },
  bmd: { name: "Bermudan Dollar", symbol: "$" },
  bnd: { name: "Brunei Dollar", symbol: "$" },
  bob: { name: "Bolivian Boliviano", symbol: "Bs" },
  brl: { name: "Brazilian Real", symbol: "R$" },
  bsd: { name: "Bahamian Dollar", symbol: "$" },
  btn: { name: "Bhutanese Ngultrum", symbol: "BTN" },
  bwp: { name: "Botswanan Pula", symbol: "P" },
  byn: { name: "Belarusian Ruble", symbol: "BYN" },
  bzd: { name: "Belize Dollar", symbol: "$" },
  cad: { name: "Canadian Dollar", symbol: "$" },
  cdf: { name: "Congolese Franc", symbol: "CDF" },
  chf: { name: "Swiss Franc", symbol: "CHF" },
  clp: { name: "Chilean Peso", symbol: "$" },
  cny: { name: "Chinese Yuan", symbol: "¥" },
  cop: { name: "Colombian Peso", symbol: "$" },
  crc: { name: "Costa Rican Colón", symbol: "₡" },
  cup: { name: "Cuban Peso", symbol: "$" },
  cve: { name: "Cape Verdean Escudo", symbol: "CVE" },
  czk: { name: "Czech Koruna", symbol: "Kč" },
  djf: { name: "Djiboutian Franc", symbol: "DJF" },
  dkk: { name: "Danish Krone", symbol: "kr" },
  dop: { name: "Dominican Peso", symbol: "$" },
  dzd: { name: "Algerian Dinar", symbol: "DZD" },
  egp: { name: "Egyptian Pound", symbol: "E£" },
  ern: { name: "Eritrean Nakfa", symbol: "ERN" },
  etb: { name: "Ethiopian Birr", symbol: "ETB" },
  eur: { name: "Euro", symbol: "€" },
  fjd: { name: "Fijian Dollar", symbol: "$" },
  fkp: { name: "Falkland Islands Pound", symbol: "£" },
  gbp: { name: "British Pound", symbol: "£" },
  gel: { name: "Georgian Lari", symbol: "₾" },
  ghs: { name: "Ghanaian Cedi", symbol: "GH₵" },
  gip: { name: "Gibraltar Pound", symbol: "£" },
  gmd: { name: "Gambian Dalasi", symbol: "GMD" },
  gnf: { name: "Guinean Franc", symbol: "FG" },
  gtq: { name: "Guatemalan Quetzal", symbol: "Q" },
  gyd: { name: "Guyanaese Dollar", symbol: "$" },
  hkd: { name: "Hong Kong Dollar", symbol: "$" },
  hnl: { name: "Honduran Lempira", symbol: "L" },
  htg: { name: "Haitian Gourde", symbol: "HTG" },
  huf: { name: "Hungarian Forint", symbol: "Ft" },
  idr: { name: "Indonesian Rupiah", symbol: "Rp" },
  ils: { name: "Israeli New Shekel", symbol: "₪" },
  inr: { name: "Indian Rupee", symbol: "₹" },
  iqd: { name: "Iraqi Dinar", symbol: "IQD" },
  irr: { name: "Iranian Rial", symbol: "IRR" },
  isk: { name: "Icelandic Króna", symbol: "kr" },
  jmd: { name: "Jamaican Dollar", symbol: "$" },
  jod: { name: "Jordanian Dinar", symbol: "JOD" },
  jpy: { name: "Japanese Yen", symbol: "¥" },
  kes: { name: "Kenyan Shilling", symbol: "KES" },
  kgs: { name: "Kyrgyz Som", symbol: "⃀" },
  khr: { name: "Cambodian Riel", symbol: "៛" },
  kmf: { name: "Comorian Franc", symbol: "CF" },
  kpw: { name: "North Korean Won", symbol: "₩" },
  krw: { name: "South Korean Won", symbol: "₩" },
  kwd: { name: "Kuwaiti Dinar", symbol: "KWD" },
  kyd: { name: "Cayman Islands Dollar", symbol: "$" },
  kzt: { name: "Kazakhstani Tenge", symbol: "₸" },
  lak: { name: "Laotian Kip", symbol: "₭" },
  lbp: { name: "Lebanese Pound", symbol: "L£" },
  lkr: { name: "Sri Lankan Rupee", symbol: "Rs" },
  lrd: { name: "Liberian Dollar", symbol: "$" },
  lsl: { name: "Lesotho Loti", symbol: "LSL" },
  lyd: { name: "Libyan Dinar", symbol: "LYD" },
  mad: { name: "Moroccan Dirham", symbol: "MAD" },
  mdl: { name: "Moldovan Leu", symbol: "MDL" },
  mga: { name: "Malagasy Ariary", symbol: "Ar" },
  mgf: { name: "Malagasy Franc", symbol: "MGF" },
  mkd: { name: "Macedonian Denar", symbol: "MKD" },
  mmk: { name: "Myanmar Kyat", symbol: "K" },
  mnt: { name: "Mongolian Tugrik", symbol: "₮" },
  mop: { name: "Macanese Pataca", symbol: "MOP" },
  mru: { name: "Mauritanian Ouguiya", symbol: "MRU" },
  mur: { name: "Mauritian Rupee", symbol: "Rs" },
  mvr: { name: "Maldivian Rufiyaa", symbol: "MVR" },
  mwk: { name: "Malawian Kwacha", symbol: "MWK" },
  mxn: { name: "Mexican Peso", symbol: "$" },
  myr: { name: "Malaysian Ringgit", symbol: "RM" },
  mzn: { name: "Mozambican Metical", symbol: "MZN" },
  nad: { name: "Namibian Dollar", symbol: "$" },
  ngn: { name: "Nigerian Naira", symbol: "₦" },
  nio: { name: "Nicaraguan Córdoba", symbol: "C$" },
  nok: { name: "Norwegian Krone", symbol: "kr" },
  npr: { name: "Nepalese Rupee", symbol: "Rs" },
  nzd: { name: "New Zealand Dollar", symbol: "$" },
  omr: { name: "Omani Rial", symbol: "OMR" },
  pab: { name: "Panamanian Balboa", symbol: "PAB" },
  pen: { name: "Peruvian Sol", symbol: "PEN" },
  pgk: { name: "Papua New Guinean Kina", symbol: "PGK" },
  php: { name: "Philippine Peso", symbol: "₱" },
  pkr: { name: "Pakistani Rupee", symbol: "Rs" },
  pln: { name: "Polish Zloty", symbol: "zł" },
  pyg: { name: "Paraguayan Guarani", symbol: "₲" },
  qar: { name: "Qatari Riyal", symbol: "QAR" },
  ron: { name: "Romanian Leu", symbol: "lei" },
  rsd: { name: "Serbian Dinar", symbol: "RSD" },
  rub: { name: "Russian Ruble", symbol: "₽" },
  rwf: { name: "Rwandan Franc", symbol: "RF" },
  sar: { name: "Saudi Riyal", symbol: "SAR" },
  sbd: { name: "Solomon Islands Dollar", symbol: "$" },
  scr: { name: "Seychellois Rupee", symbol: "SCR" },
  sdg: { name: "Sudanese Pound", symbol: "SDG" },
  sek: { name: "Swedish Krona", symbol: "kr" },
  sgd: { name: "Singapore Dollar", symbol: "$" },
  shp: { name: "St. Helena Pound", symbol: "£" },
  sle: { name: "Sierra Leonean Leone", symbol: "SLE" },
  sos: { name: "Somali Shilling", symbol: "SOS" },
  srd: { name: "Surinamese Dollar", symbol: "$" },
  srg: { name: "Surinamese Guilder", symbol: "SRG" },
  ssp: { name: "South Sudanese Pound", symbol: "£" },
  stn: { name: "São Tomé & Príncipe Dobra", symbol: "Db" },
  syp: { name: "Syrian Pound", symbol: "£" },
  szl: { name: "Swazi Lilangeni", symbol: "SZL" },
  thb: { name: "Thai Baht", symbol: "฿" },
  tjs: { name: "Tajikistani Somoni", symbol: "TJS" },
  tmt: { name: "Turkmenistani Manat", symbol: "TMT" },
  tnd: { name: "Tunisian Dinar", symbol: "TND" },
  top: { name: "Tongan Paʻanga", symbol: "T$" },
  try: { name: "Turkish Lira", symbol: "₺" },
  ttd: { name: "Trinidad & Tobago Dollar", symbol: "$" },
  twd: { name: "New Taiwan Dollar", symbol: "$" },
  tzs: { name: "Tanzanian Shilling", symbol: "TZS" },
  uah: { name: "Ukrainian Hryvnia", symbol: "₴" },
  ugx: { name: "Ugandan Shilling", symbol: "UGX" },
  usd: { name: "US Dollar", symbol: "$" },
  uyu: { name: "Uruguayan Peso", symbol: "$" },
  uzs: { name: "Uzbekistani Som", symbol: "UZS" },
  ves: { name: "Venezuelan Bolívar", symbol: "VES" },
  vnd: { name: "Vietnamese Dong", symbol: "₫" },
  vuv: { name: "Vanuatu Vatu", symbol: "VUV" },
  wst: { name: "Samoan Tala", symbol: "WST" },
  xaf: { name: "Central African CFA Franc", symbol: "FCFA" },
  xcd: { name: "East Caribbean Dollar", symbol: "$" },
  xcg: { name: "Caribbean guilder", symbol: "Cg." },
  xof: { name: "West African CFA Franc", symbol: "F CFA" },
  xpf: { name: "CFP Franc", symbol: "CFPF" },
  yer: { name: "Yemeni Rial", symbol: "YER" },
  zar: { name: "South African Rand", symbol: "R" },
  zmw: { name: "Zambian Kwacha", symbol: "ZK" },
  zwg: { name: "Zimbabwean Gold", symbol: "ZWG" },
};
