/**
 * Vendors the text face into `public/fonts/` and writes `src/styles/fonts.css`.
 *
 *     bun run --cwd apps/landing fonts
 *
 * The page makes no third-party requests at runtime — that is a Lighthouse
 * requirement and also the page's own argument — so nothing may point at
 * fonts.gstatic.com. Google's CSS2 endpoint already serves one woff2 per
 * unicode-range, which is exactly the per-locale subsetting the brief asks for:
 * a visitor on `/en/` never downloads the Cyrillic file. Re-run only when a
 * family or weight changes; the output is committed.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

const ROOT = join(dirname(new URL(import.meta.url).pathname), "..");
const FONT_DIR = join(ROOT, "public", "fonts");
const CSS_OUT = join(ROOT, "src", "styles", "fonts.css");

// A modern UA is what makes the endpoint answer with woff2 instead of ttf.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

type Family = {
  /** Google's family spec, e.g. `Nunito+Sans:wght@300..900`. */
  query: string;
  slug: string;
  subsets: string[];
};

const FAMILIES: Family[] = [
  {
    query: "Nunito:wght@400..800",
    slug: "nunito",
    subsets: ["latin", "latin-ext", "cyrillic"],
  },
];

/** One `/* subset *\/ @font-face { … }` pair out of Google's stylesheet. */
type Face = { subset: string; block: string };

const parseFaces = (css: string): Face[] => {
  const faces: Face[] = [];
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  for (const match of css.matchAll(re)) {
    const [, subset, block] = match;
    if (subset && block) faces.push({ subset, block });
  }
  return faces;
};

const field = (block: string, name: string): string => {
  const found = block.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1];
  if (!found) throw new Error(`missing ${name} in @font-face`);
  return found.trim();
};

const main = async () => {
  await mkdir(FONT_DIR, { recursive: true });
  await mkdir(dirname(CSS_OUT), { recursive: true });
  const rules: string[] = [
    "/* Generated by scripts/fetch-fonts.ts — do not edit by hand. */",
  ];

  for (const family of FAMILIES) {
    const res = await fetch(
      `https://fonts.googleapis.com/css2?family=${family.query}&display=swap`,
      { headers: { "User-Agent": UA } },
    );
    if (!res.ok) throw new Error(`${family.slug}: HTTP ${res.status}`);
    const css = await res.text();

    const wanted = parseFaces(css).filter((face) =>
      family.subsets.includes(face.subset),
    );
    // A static family repeats every subset once per weight, so count distinct
    // subsets rather than faces.
    const found = new Set(wanted.map((face) => face.subset));
    const missing = family.subsets.filter((subset) => !found.has(subset));
    if (missing.length > 0) {
      throw new Error(`${family.slug}: no ${missing.join(", ")} subset served`);
    }

    for (const { subset, block } of wanted) {
      const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
      if (!url) throw new Error(`${family.slug}/${subset}: no woff2 url`);

      const weight = field(block, "font-weight");
      const file = `${family.slug}-${weight.replace(/\s+/g, "-")}-${subset}.woff2`;
      const bytes = await fetch(url).then((r) => r.arrayBuffer());
      await writeFile(join(FONT_DIR, file), new Uint8Array(bytes));

      rules.push(
        "@font-face {",
        `  font-family: ${field(block, "font-family")};`,
        `  font-style: ${field(block, "font-style")};`,
        `  font-weight: ${weight};`,
        "  font-display: swap;",
        `  src: url("/fonts/${file}") format("woff2");`,
        `  unicode-range: ${field(block, "unicode-range")};`,
        "}",
      );
      console.log(`${file}  ${(bytes.byteLength / 1024).toFixed(1)} KB`);
    }
  }

  await writeFile(CSS_OUT, `${rules.join("\n")}\n`);
};

await main();
