name: Post Release

on:
  push:
    branches:
      - main

jobs:
  back-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }} # Using PAT to allow pushing to protected branches

      - name: Set Git Config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Merge Main into Dev
        run: |
          git checkout dev
          git pull origin dev
          git merge origin/main --no-edit -m "chore: sync release from main to dev [skip ci]"
          git push origin dev
